### ISSUE TITLE
Несколько вопросов по работе с протоколом J1850 VPW

### ISSUE THREAD

**Issue by vladpopov** [iiryzhkov/j1850_arduino#10]
Илья, привет

Ты один из немногих, кто выкладывает свои наработки по J1850. У меня есть несколько вопросов по этой теме.

Можешь связаться со мной?
Телеграм vladpopov_at_live_dot_com
Почта vladpopov@live.com

--Влад

**Comment by aid696** [comment]
я не илья у него другой адрес посмотри внимательноSent from my Verizon Wireless 4G LTE Smartphone

-------- Original message --------
