### ISSUE TITLE
Example Device

### ISSUE THREAD

**Issue by santiagax99** [iiryzhkov/j1850_arduino#8]
Can you provide example device schematics to connect SAE J1850 (from OBD II) to Arduino ?

**Comment by iiryzhkov** [comment]
https://github.com/iiryzhkov/j1850_arduino/blob/attempt_to_send/Tools/connection_to_arduino.png

**Comment by iiryzhkov** [comment]
> Can you provide example device schematics to connect SAE J1850 (from OBD II) to Arduino ?

https://github.com/iiryzhkov/j1850_arduino/blob/attempt_to_send/Tools/connection_to_arduino.png
